src/DEVSEARCH/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("projects.urls")),
    path("account/", include("users.urls")),
    path("user/", include("user_profiles.urls")),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="reset_password_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="reset_password_complete.html"
        ),
        name="password_reset_complete",
    ),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/user_profiles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("profiles", views.profiles, name="profiles"),
    path("profile/<str:pk>", views.profile_detail, name="profile_detail"),
    path("user-account", views.user_account, name="user_account"),
    path("edit-user-account", views.edit_user_account, name="edit_user_account"),
    path("create-skill", views.create_skill, name="create_skill"),
    path("update-skill/<str:pk>", views.update_skill, name="update_skill"),
    path("delete-skill/<str:pk>", views.delete_skill, name="delete_skill"),
    path("user-inbox", views.inbox, name="user_inbox"),
    path("message/<str:pk>", views.view_messages, name="view_messages"),
    path("send-message/<str:pk>", views.create_message, name="create_message"),
]

src/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("register", views.RegistrationView.as_view(), name="register"),
    path("activate/<uidb64>/<token>/", views.verification, name="activate"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_request, name="logout"),
]

src/projects/models.py
from django.db import models
import uuid
from user_profiles.models import Profile

# Create your models here.


class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(
        default="default.jpg",
        upload_to="images/user_uploaded_content",
        null=True,
    )
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField("Tag", blank=True)
    vote_total = models.IntegerField(null=True, blank=True, default=0)
    vote_ratio = models.IntegerField(null=True, blank=True, default=0)
    source_code = models.CharField(max_length=2000, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, unique=True, editable=False
    )

    def __str__(self) -> str:
        return f"{self.title}-->{self.id}"

    @property
    def reviewrs(self) -> list():
        """Returns a list of reviewrs of a given project."""
        return self.review_set.all().values_list("review_owner", flat=True)


    @property
    def get_vote_count(self):
        reviews = self.reviews_set.all()
        upvotes = reviews.filter(value="up").count()
        ratio = (upvotes / reviews.count()) * 100
        self.vote_total = reviews.count()
        self.vote_ratio = ratio
        self.save()



# text choices value field in Review Model
class VoteTypes(models.TextChoices):
    UP_VOTE = ("up", "Up vote")
    DOWN_VOTE = ("down", "Down vote")


class Review(models.Model):
    review_owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=50, choices=VoteTypes.choices)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, unique=True, editable=False
    )

    class Meta:
        # one profile can have only one review per project
        # unique_together will take care of that
        unique_together = [
            ["review_owner", "project"],
        ]
        ordering = ["-created"]

    def __str__(self) -> str:
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, unique=True, editable=False
    )

    def __str__(self) -> str:
        return self.name

src/user_profiles/models.py
from django.db import models
from django.contrib.auth import get_user_model
import uuid


User = get_user_model()


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=500)
    email_verified = models.BooleanField(default=False)
    location = models.CharField(max_length=200, blank=True, null=True)
    short_intro = models.CharField(max_length=200)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(
        null=True,
        upload_to="images/user_profiles",
        default="images/user_profiles/avatar7.png",
    )
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self):
        return str(self.user.email)

    def get_full_name(self):
        """Returns the full name of the User Profile."""
        return f"{self.first_name} {self.last_name}"

    class Meta:
        ordering = ["-created"]


class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self):
        return self.name


class Message(models.Model):
    sender = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True, blank=True
    )
    recipient = models.ForeignKey(
        Profile,
        on_delete=models.SET_NULL,
        related_name="messages",
        null=True,
        blank=True,
    )
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    subject = models.CharField(max_length=255)
    is_read = models.BooleanField(default=False, null=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self) -> str:
        return self.subject

    class Meta:
        ordering = ["is_read", "-created"]

src/user_profiles/forms.py
from django.forms import ModelForm
from .models import Profile, Skill, Message
from django import forms


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ("user", "email_verified")

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        # self.fields["profile_image"].widget = forms.ImageField()

        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})


class SkillForm(ModelForm):
    class Meta:
        model = Skill
        exclude = ("owner",)

    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})


class UnauthenticatedMessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ("name", "email", "subject", "body")

    def __init__(self, *args, **kwargs):
        super(UnauthenticatedMessageForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})


class AuthenticatedMessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ("subject", "body")

    def __init__(self, *args, **kwargs):
        super(AuthenticatedMessageForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})

src/user_profiles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404
from .models import Profile, Skill, Message
from .forms import (
    ProfileForm,
    SkillForm,
    UnauthenticatedMessageForm,
    AuthenticatedMessageForm,
)
from django.contrib import messages


# Create your views here.


def profiles(request):
    page_num = request.GET.get("page")
    search_query = ""
    if request.GET.get("search_query"):
        search_query = request.GET.get("search_query")

    skills_queryset = Skill.objects.filter(name__icontains=search_query)

    profiles = Profile.objects.distinct().filter(
        Q(first_name__icontains=search_query)
        | Q(last_name__icontains=search_query)
        | Q(short_intro__icontains=search_query)
        # we are checking if the skills in a profile are available in
        # the skills_queryset
        | Q(skill__in=skills_queryset)
    )
    project_paginator = Paginator(profiles, 3)
    page = project_paginator.get_page(page_num)
    context = {"page": page, "search_query": search_query}
    return render(request, "user_profiles/profiles.html", context)


def profile_detail(request, pk):
    profile = Profile.objects.get(pk=pk)
    top_skills = profile.skill_set.exclude(description__iexact="")
    other_skills = profile.skill_set.filter(description="")
    context = {
        "profile": profile,
        "top_skills": top_skills,
        "other_skills": other_skills,
    }

    return render(request, "user_profiles/profile_detail.html", context)


@login_required(login_url="login")
def user_account(request):
    profile = request.user.profile
    context = {"profile": profile}
    return render(request, "user_profiles/account.html", context)


@login_required(login_url="login")
def edit_user_account(request):
    profile = Profile.objects.get(pk=request.user.profile.id)
    form = ProfileForm(instance=profile)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect("user_account")

    context = {
        "form": form,
    }
    return render(request, "user_profiles/profile_form.html", context)


@login_required(login_url="login")
def create_skill(request):
    form = SkillForm()
    if request.method == "POST":
        form = SkillForm(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.owner = request.user.profile
            skill.save()
            messages.success(request, "Skill was added successfully.")
            return redirect("user_account")
    context = {
        "form": form,
    }
    return render(request, "user_profiles/skill_form.html", context)


@login_required(login_url="login")
def update_skill(request, pk):
    skill = Skill.objects.get(pk=pk)
    if skill.owner != request.user.profile:
        return redirect("projects")
    form = SkillForm(instance=skill)
    if request.method == "POST":
        form = SkillForm(request.POST, instance=skill)
        if form.is_valid():
            form.save()
            messages.success(request, "Skill was updated successfully.")
            return redirect("user_account")
    context = {
        "form": form,
    }
    return render(request, "user_profiles/skill_form.html", context)


@login_required(login_url="login")
def delete_skill(request, pk):
    skill = Skill.objects.get(pk=pk)
    if skill.owner != request.user.profile:
        return redirect("user_account")
    skill.delete()
    messages.info(request, "Skill was deleted successfully.")
    return redirect("user_account")


@login_required(login_url="login")
def inbox(request):
    profile = request.user.profile
    messages_queryset = profile.messages.all()
    unread_messages_count = messages_queryset.filter(is_read=False).count()
    context = {
        "messages_queryset": messages_queryset,
        "unread_messages_count": unread_messages_count,
    }
    return render(request, "user_profiles/inbox.html", context)


@login_required(login_url="login")
def view_messages(request, pk):
    profile = request.user.profile
    message_obj = profile.messages.get(pk=pk)
    if message_obj.is_read is False:
        message_obj.is_read = True
        message_obj.save()
    context = {
        "message_obj": message_obj,
    }
    return render(request, "user_profiles/message.html", context)


def create_message(request, pk):
    recipient = Profile.objects.get(pk=pk)
    #- if user is logged in
    if request.user.is_authenticated:
        form = AuthenticatedMessageForm()
        if request.method == "POST":
            form = AuthenticatedMessageForm(request.POST)
            if form.is_valid():
                message_obj = form.save(commit=False)
                message_obj.sender = request.user.profile
                message_obj.recipient = recipient
                message_obj.name = request.user.profile.get_full_name()
                message_obj.email = request.user.profile.email
                message_obj.save()
                return redirect("profile_detail", pk=recipient.id)
        context = {"form": form, "recipient": recipient}
        return render(request, "user_profiles/message_form.html", context)

    form = UnauthenticatedMessageForm()
    if request.method == "POST":
        form = UnauthenticatedMessageForm(request.POST)
        if form.is_valid():
            message_obj = form.save(commit=False)
            message_obj.sender = None
            message_obj.recipient = recipient
            message_obj.save()
            return redirect("profile_detail", pk=recipient.id)
    context = {"form": form, "recipient": recipient}
    return render(request, "user_profiles/message_form.html", context)

src/templates/user_profiles/account.html
{% extends "main.html" %}
{% block content %}
    <main class="settingsPage profile my-md">
        <div class="container">
            <div class="layout">
                <div class="column column--1of3">
                    <div class="card text-center">
                        <div class="card__body dev">
                            <a class="tag tag--pill tag--main settings__btn"
                               href="{% url "edit_user_account" %}"><i class="im im-edit"></i> Edit</a>
                            <img class="avatar avatar--xl dev__avatar"
                                 src="{{ profile.profile_image.url }}">
                            <h2 class="dev__name">{{ profile.get_full_name }}</h2>
                            <p class="dev__title">{{ profile.short_intro }}</p>
                            {% if profile.location %}
                                <p class="dev__location">{{ profile.location }}</p>
                            {% else %}
                                <p class="dev__location">Developer Location is not available</p>
                            {% endif %}
                            <ul class="dev__social">
                                {% if profile.social_github %}
                                    <li>
                                        <a title="Github" href="#" target="_blank"><i class="im im-github"></i></a>
                                    </li>
                                {% endif %}
                                {% if profile.social_twitter %}
                                    <li>
                                        <a title="Twitter" href="#" target="_blank"><i class="im im-twitter"></i></a>
                                    </li>
                                {% endif %}
                                {% if profile.social_linkedin %}
                                    <li>
                                        <a title="LinkedIn" href="#" target="_blank"><i class="im im-linkedin"></i></a>
                                    </li>
                                {% endif %}
                                {% if profile.social_website %}
                                    <li>
                                        <a title="Personal Website" href="#" target="_blank"><i class="im im-globe"></i></a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="column column--2of3">
                    <div class="devInfo">
                        <h3 class="devInfo__title">About Me</h3>
                        <p class="devInfo__about">{{ profile.bio }}</p>
                    </div>
                    <div class="settings">
                        <h3 class="settings__title">Skills</h3>
                        <a class="tag tag--pill tag--sub settings__btn tag--lg"
                           href="{% url 'create_skill' %}"><i class="im im-plus"></i> Add Skill</a>
                    </div>
                    <table class="settings__table">
                        {% for skill in profile.skill_set.all %}
                            <tr>
                                <td class="settings__tableInfo">
                                    <h4>{{ skill.name }}</h4>
                                    <p>{{ skill.description|slice:"150" }}</p>
                                </td>
                                <td class="settings__tableActions">
                                    <a class="tag tag--pill tag--main settings__btn"
                                       href="{% url 'update_skill' skill.id %}"><i class="im im-edit"></i> Edit</a>
                                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete_skill' skill.id %}"><i class="im im-x-mark-circle-o"></i>
                            Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            <div class="settings">
                <h3 class="settings__title">Projects</h3>
                <a class="tag tag--pill tag--sub settings__btn tag--lg"
                   href="{% url 'create_project' %}"><i class="im im-plus"></i> Add Project</a>
            </div>
            <table class="settings__table">
                {% for project in profile.project_set.all %}
                    <tr>
                        <td class="settings__thumbnail">
                            <a href="{% url "project" project.id %}">
                                <img src="{{ project.featured_image.url }}" alt="Project Thumbnail" />
                            </a>
                        </td>
                        <td class="settings__tableInfo">
                            <a href="{% url "project" project.id %}">{{ project.title }}</a>
                            <p>{{ project.description|slice:"70" }}</p>
                        </td>
                        <td class="settings__tableActions">
                            <a class="tag tag--pill tag--main settings__btn"
                               href="{% url 'update_project' project.id %}"><i class="im im-edit"></i> Edit</a>
                        <a class="tag tag--pill tag--main settings__btn"
                           href="{% url 'delete_project' project.id %}"><i class="im im-x-mark-circle-o"></i>
                    Delete</a>
                </td>
            </tr>
        {% endfor %}
    </table>
</div>
</div>
</div>
</main>
{% endblock %}

src/templates/user_profiles/inbox.html
{% extends 'main.html' %}
{% block content %}
    <main class="inbox my-xl">
        <div class="content-box">
            <h3 class="inbox__title">
                New Messages(<span>{{ unread_messages_count }}</span>)
            </h3>
            <ul class="messages">
                {% for message in messages_queryset %}
                    <li class="message {% if not message.is_read %}message--unread {% endif %} ">
                        <a href="{% url 'view_messages' message.id %}">
                            <span class="message__author">{{ message.name }}</span>
                            <span class="message__subject">{{ message.subject }}</span>
                            <span class="message__date">{{ message.created }}</span>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </main>
{% endblock %}

src/templates/user_profiles/message.html
{% extends 'main.html' %}
{% block content %}
    <main class="messagePage my-xl">
        <div class="content-box">
            <div class="message">
                <a class="backButton" href="{{ request.META.HTTP_REFERER }}"><i class="im im-angle-left"></i></a>
                <h2 class="message__subject">
                    {{ message_obj.subject }}
                </h4>
                <a href="profile.html" class="message__author">{{ message_obj.name }}</a>
                <p class="message__date">{{ messsage_obj.created }}</p>
                <div class="message__body">{{ message_obj.body|linebreaksbr }}</div>
            </div>
        </div>
    </main>
{% endblock %}

src/templates/user_profiles/message_form.html
{% extends 'main.html' %}
{% block content %}
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{{ request.META.HTTP_REFERER }}"><i class="im im-angle-left"></i></a>
                <br>
                <form class="form"
                      action="{% url 'create_message' recipient.id %}"
                      method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form__field">
                            <label for="formInput#text">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <!-- Input:Text -->
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
{% endblock %}

src/templates/user_profiles/profile_detail.html
{% extends "main.html" %}
{% block content %}
    <main class="profile my-md">
        <div class="container">
            <div class="layout">
                <div class="column column--1of3">
                    <div class="card text-center">
                        <div class="card__body dev">
                            <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}">
                            <h2 class="dev__name">{{ profile.first_name }} {{ profile.last_name }}</h2>
                            <p class="dev__title">{{ profile.short_intro }}</p>
                            {% if profile.location %}
                                <p class="dev__location">{{ profile.location }}</p>
                            {% else %}
                                <p class="dev__location">Developer Location is not available</p>
                            {% endif %}
                            <ul class="dev__social">
                                {% if profile.social_github %}
                                    <li>
                                        <a title="Github" href="#" target="_blank"><i class="im im-github"></i></a>
                                    </li>
                                {% endif %}
                                {% if profile.social_twitter %}
                                    <li>
                                        <a title="Twitter" href="#" target="_blank"><i class="im im-twitter"></i></a>
                                    </li>
                                {% endif %}
                                {% if profile.social_linkedin %}
                                    <li>
                                        <a title="LinkedIn" href="#" target="_blank"><i class="im im-linkedin"></i></a>
                                    </li>
                                {% endif %}
                                {% if profile.social_website %}
                                    <li>
                                        <a title="Personal Website" href="#" target="_blank"><i class="im im-globe"></i></a>
                                    </li>
                                {% endif %}
                            </ul>
                            {% if not request.user == profile.user %}
                            <a href="{% url 'create_message' profile.id %}" class="btn btn--sub btn--lg">Send Message</a>
                            {% endif %}

                        </div>
                    </div>
                </div>
                <div class="column column--2of3">
                    <div class="devInfo">
                        <h3 class="devInfo__title">About Me</h3>
                        <p class="devInfo__about">{{ profile.bio }}</p>
                    </div>
                    <div class="devInfo">
                        <h3 class="devInfo__title">Skills</h3>
                        <div class="devInfo__skills">
                            {% for skill in top_skills %}
                                <div class="devSkill">
                                    <h4 class="devSkill__title">{{ skill }}</h4>
                                    <p class="devSkill__info">{{ skill.description }}</p>
                                </div>
                            {% endfor %}
                            <h3 class="devInfo__subtitle">Other Skills</h3>
                            <div class="devInfo__otherSkills">
                                {% for skill in other_skills %}
                                    <span class="tag tag--pill tag--sub tag--lg">
                                        <small>{{ skill }}</small>
                                    </span>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="devInfo">
                        <h3 class="devInfo__title">Projects</h3>
                        <div class="grid grid--two">
                            {% for project in profile.project_set.all %}
                                <div class="column">
                                    <div class="card project">
                                        <a href="{% url "project" pk=project.id %}" class="project">
                                            <img class="project__thumbnail"
                                                 src="{{ project.featured_image.url }}"
                                                 alt="project thumbnail" />
                                            <div class="card__body">
                                                <h3 class="project__title">{{ project.title }}</h3>
                                                <p>
                                                    <a class="project__author"
                                                       href="{% url "profile_detail" pk=project.owner.id %}">{{ project.owner.name }}</a>
                                                </p>
                                                <p class="project--rating">
                                                    <span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Postitive
                                                    Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize:"s" }}))
                                                </p>
                                                <div class="project__tags">
                                                    {% for tag in project.tags.all %}
                                                        <span class="tag tag--pill tag--main">
                                                            <small>{{ tag }}</small>
                                                        </span>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

src/templates/user_profiles/profile_form.html
{% extends "main.html" %}
{% block content %}
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'user_account' %}"><i class="im im-angle-left"></i></a>
                <br>
                <form class="form" action="{% url 'edit_user_account' %}"
                      method="post"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- Input:Text -->
                    {% for field in form %}
                        <div class="form__field">
                            <label for="formInput#text">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <!-- Input:Text -->
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
{% endblock %}